welcomeMessage: "Spring Batch - prod"

spring.batch.job.enabled: false
spring.batch.jmx.enabled: true
spring.main.banner-mode: off

spring:
  config:
    activate:
      on-profile: prod

primary:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/batch
    username: batch_user
    password: password

batch:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/batch
    username: batch_user
    password: password
    table-prefix: MM_

---

spring:
  profiles: pki

primary:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/batch_pki
    username: batch_user_pki
    password: password

batch:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/batch_pki
    username: batch_user_pki
    password: password
    table-prefix: M2_