welcomeMessage: "Spring Batch - prod"

spring.batch.job.enabled: false
spring.main.banner-mode: off

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    platform: POSTGRES
    url: jdbc:postgresql://localhost:5432/batch
    username: batch_user
    password: password
  batch:
    initialize-schema: always

#spring.datasource.schema: classpath:/schema.sql
#spring.datasource.continue-on-error: true
#spring.batch.initialize-schema: always
