welcomeMessage: "Spring Batch - prod"

spring.batch.job.enabled: false
spring.batch.jmx.enabled: true
spring.main.banner-mode: off

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    platform: POSTGRES
    url: jdbc:postgresql://localhost:5432/batch
    username: batch_user
    password: password
  batch:
    initialize-schema: never
    table-prefix: MM_

#spring.datasource.schema: classpath:/schema-postgres.sql
#spring.datasource.continue-on-error: true
#spring.batch.initialize-schema: always
#spring.batch.table-prefix: MM_

