welcomeMessage: "Spring Batch - prod"

spring.batch.job.enabled: false
spring.batch.jmx.enabled: true
spring.main.banner-mode: off

spring:
  config:
    activate:
      on-profile: prod

datasource:
  primary:
    jdbcUrl: jdbc:postgresql://localhost:5432/batch
    username: batch_user
    password: password
  batch:
    jdbcUrl: jdbc:postgresql://localhost:5432/batch
    username: batch_user
    password: password
    table-prefix: MM_

---

spring:
  profiles: pki

datasource:
  primary:
    jdbcUrl: jdbc:postgresql://localhost:5432/batch
    username: batch_user
    password: password
  batch:
    jdbcUrl: jdbc:postgresql://localhost:5432/batch
    username: batch_user
    password: password
    table-prefix: MM_