DROP TABLE  IF EXISTS MM_STEP_EXECUTION_CONTEXT;
DROP TABLE  IF EXISTS MM_JOB_EXECUTION_CONTEXT;
DROP TABLE  IF EXISTS MM_STEP_EXECUTION;
DROP TABLE  IF EXISTS MM_JOB_EXECUTION_PARAMS;
DROP TABLE  IF EXISTS MM_JOB_EXECUTION;
DROP TABLE  IF EXISTS MM_JOB_INSTANCE;

DROP SEQUENCE  IF EXISTS MM_STEP_EXECUTION_SEQ ;
DROP SEQUENCE  IF EXISTS MM_JOB_EXECUTION_SEQ ;
DROP SEQUENCE  IF EXISTS MM_JOB_SEQ ;